// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Programatica.DummyApp.Data;

namespace Programatica.DummyApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200414023601_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Programatica.DummyApp.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("CreatedUser");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDestroyed");

                    b.Property<bool>("IsSystem");

                    b.Property<DateTime?>("LastDestroyedDate");

                    b.Property<string>("LastDestroyedUser");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("LastModifiedUser");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<Guid>("SystemId");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@mail.com",
                            IsDestroyed = false,
                            IsSystem = false,
                            Name = "User1",
                            Password = "123",
                            SystemId = new Guid("0fd49aff-1b6e-4ae4-b3d4-6c4622d6a15b")
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@mail.com",
                            IsDestroyed = false,
                            IsSystem = false,
                            Name = "User2",
                            Password = "123",
                            SystemId = new Guid("c0be270e-6d5a-4b0e-8964-1105253af7cd")
                        });
                });

            modelBuilder.Entity("Programatica.Framework.Data.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<string>("ContentFunction");

                    b.Property<int>("ContentId");

                    b.Property<Guid>("ContentSystemId");

                    b.Property<string>("ContentType");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("CreatedUser");

                    b.Property<bool>("IsDestroyed");

                    b.Property<bool>("IsSystem");

                    b.Property<DateTime?>("LastDestroyedDate");

                    b.Property<string>("LastDestroyedUser");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("LastModifiedUser");

                    b.Property<Guid>("SystemId");

                    b.HasKey("Id");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("Programatica.Framework.Data.Models.TrackChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditId");

                    b.Property<string>("Comments");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("CreatedUser");

                    b.Property<string>("FieldName");

                    b.Property<bool>("IsDestroyed");

                    b.Property<bool>("IsSystem");

                    b.Property<DateTime?>("LastDestroyedDate");

                    b.Property<string>("LastDestroyedUser");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("LastModifiedUser");

                    b.Property<string>("NewValue");

                    b.Property<string>("OldValue");

                    b.Property<Guid>("SystemId");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("TrackChanges");
                });

            modelBuilder.Entity("Programatica.Framework.Data.Models.TrackChange", b =>
                {
                    b.HasOne("Programatica.Framework.Data.Models.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
